baseURL = "https://chahat-m.github.io/"
languageCode = "en-us"
paginate = 6
theme = "portio-hugo"
title = "Chahat"
# Main Menu
[[menu.main]]
name = "Home"
url = "#home"
weight = 1
[[menu.main]]
name = "About"
url = "#about"
weight = 2
[[menu.main]]
name = "Extracurricular"
url = "#service"
weight = 3
[[menu.main]]
name = "Projects"
url = "#portfolio"
weight = 4
[[menu.main]]
name = "Resume"
url = "#resume"
weight = 5
[[menu.main]]
name = "Skills"
url = "#skills"
weight = 6
[[menu.main]]
name = "Blog"
url = "#blog"
weight = 7
[[menu.main]]
name = "Contact"
url = "#contact"
weight = 8

# Sitemap Menu
[[menu.sitemap]]
name = "About me"
url = "#about"
weight = 1
[[menu.sitemap]]
name = "Latest Article"
url = "#blog"
weight = 2

[params]
blogPageURL = "blog"
contactLink = "contact"
copyright = "All right reserved copyright © Portio 2020"
footerLogo = "images/contact/widget-logo.png"
# We're using formspree.io for form handling, paste your formspree url below
fabformURL  = "https://fabform.io/f/JpTXRUa"
googleAnalytics = "YOUR GOOGLE ANALYTICS CODE"
logo = "images/site-navigation/logo.png"

[params.address]
address = "Room No. 332,Raman House, IIIT Naya Raipur, Chhatisgarh"
email = "chahat20101@iiitnr.edu.in"
openingHours = "Open to work"
phone = "+(91) 8962161153"

[params.map]
APIkey = "YOUR GOOGLE MAP API"
latitude = "23.7783741"
longitude = "90.3746808"
pinImage = "images/pin.png"

# Social icons
[[params.social]]
icon = "fa-linkedin-square"
url = "https://www.linkedin.com/in/chahat-mittal-093bb3200/"
weight = 1
[[params.social]]
icon = "fa-github-square"
url = "https://github.com/Chahat-M"
weight = 2
